[package]
name = "eyebot2"
version = "0.1.0"
edition = "2024"
authors = ['eyemotif']

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
urlencoding = "2.1.3"
